2020-06-03 17:43:59 [scrapy.utils.log] INFO: Scrapy 2.0.1 started (bot: sobooks)
2020-06-03 17:43:59 [scrapy.utils.log] INFO: Versions: lxml 4.5.0.0, libxml2 2.9.9, cssselect 1.1.0, parsel 1.5.2, w3lib 1.21.0, Twisted 20.3.0, Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)], pyOpenSSL 19.1.0 (OpenSSL 1.1.1d  10 Sep 2019), cryptography 2.8, Platform Windows-10-10.0.17763-SP0
2020-06-03 17:43:59 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'sobooks',
 'LOG_FILE': 'test',
 'LOG_LEVEL': 'INFO',
 'NEWSPIDER_MODULE': 'sobooks.spiders',
 'SPIDER_MODULES': ['sobooks.spiders']}
2020-06-03 17:43:59 [scrapy.extensions.telnet] INFO: Telnet Password: b51f0e764c0834e5
2020-06-03 17:43:59 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2020-06-03 17:44:00 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2020-06-03 17:44:00 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2020-06-03 17:44:00 [scrapy.middleware] INFO: Enabled item pipelines:
['sobooks.pipelines.MysqlPipline']
2020-06-03 17:44:00 [scrapy.core.engine] INFO: Spider opened
2020-06-03 17:44:00 [sotag] INFO: sotag connect mysql:{'host': '127.0.0.1', 'port': 3306, 'user': 'root', 'db': 'sobooks', 'passwd': ''}
2020-06-03 17:44:00 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2020-06-03 17:44:00 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '小说'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '小说'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '小说'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '小说' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '文学'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '文学'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '文学'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '文学' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '历史'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '历史'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '历史'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '历史' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '日本'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '日本'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '日本'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '日本' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '管理'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '管理'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '管理'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '管理' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '科普'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '科普'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '科普'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '科普' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '推理'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '推理'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '推理'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '推理' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '社会'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '社会'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '社会'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '社会' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '传记'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '传记'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '传记'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '传记' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '经济'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '经济'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '经济'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '经济' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '悬疑'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '悬疑'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '悬疑'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '悬疑' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '美国'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '美国'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '美国'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '美国' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '哲学'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '哲学'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '哲学'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '哲学' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '心理'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '心理'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '心理'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '心理' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '金融'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '金融'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '金融'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '金融' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '商业'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '商业'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '商业'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '商业' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '随笔'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '随笔'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '随笔'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '随笔' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '经典'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '经典'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '经典'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '经典' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '思维'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '思维'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '思维'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '思维' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '投资'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '投资'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '投资'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '投资' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '文化'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '文化'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '文化'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '文化' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '科幻'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '科幻'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '科幻'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '科幻' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '励志'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '励志'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '励志'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '励志' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '成长'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '成长'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '成长'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '成长' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '英国'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '英国'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '英国'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '英国' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '中国'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '中国'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '中国'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '中国' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '政治'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '政治'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '政治'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '政治' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '纪实'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '纪实'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '纪实'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '纪实' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '艺术'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '艺术'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '艺术'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '艺术' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '生活'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '生活'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '生活'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '生活' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '职场'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '职场'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '职场'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '职场' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '科学'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '科学'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '科学'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '科学' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '互联网'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '互联网'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '互联网'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '互联网' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '漫画'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '漫画'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '漫画'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '漫画' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '散文'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '散文'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '散文'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '散文' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '法国'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '法国'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '法国'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '法国' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '股票'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '股票'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '股票'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '股票' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '奇幻'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '奇幻'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '奇幻'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '奇幻' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '营销'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '营销'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '营销'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '营销' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '二战'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '二战'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '二战'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '二战' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '战争'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '战争'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '战争'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '战争' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '德国'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '德国'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '德国'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '德国' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '创业'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '创业'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '创业'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '创业' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '女性'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '女性'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '女性'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '女性' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '军事'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '军事'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '军事'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '军事' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '名著'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '名著'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '名著'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '名著' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '学习'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '学习'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '学习'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '学习' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '爱情'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '爱情'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '爱情'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '爱情' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '人物'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '人物'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '人物'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '人物' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '世界'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '世界'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '世界'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '世界' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '绘本'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '绘本'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '绘本'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '绘本' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '理财'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '理财'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '理财'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '理财' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '教育'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '教育'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '教育'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '教育' pour la clef 'namekey'")
2020-06-03 17:44:01 [sotag] INFO: get item:{'name': '国学'}
2020-06-03 17:44:01 [sotag] INFO: sotag process_item:{'name': '国学'}
2020-06-03 17:44:01 [scrapy.core.scraper] ERROR: Error processing {'name': '国学'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 66, in process_item
    cursor.execute("""insert into tags (name) value (%s) """,(item['name']))
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "f:\programdata\anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicata du champ '国学' pour la clef 'namekey'")
2020-06-03 17:44:01 [scrapy.core.engine] INFO: Closing spider (finished)
2020-06-03 17:44:01 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 210,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 9085,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'elapsed_time_seconds': 0.93901,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2020, 6, 3, 9, 44, 1, 575459),
 'log_count/ERROR': 54,
 'log_count/INFO': 119,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2020, 6, 3, 9, 44, 0, 636449)}
2020-06-03 17:44:01 [scrapy.core.engine] INFO: Spider closed (finished)
2020-06-03 17:47:25 [scrapy.utils.log] INFO: Scrapy 2.0.1 started (bot: sobooks)
2020-06-03 17:47:25 [scrapy.utils.log] INFO: Versions: lxml 4.5.0.0, libxml2 2.9.9, cssselect 1.1.0, parsel 1.5.2, w3lib 1.21.0, Twisted 20.3.0, Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)], pyOpenSSL 19.1.0 (OpenSSL 1.1.1d  10 Sep 2019), cryptography 2.8, Platform Windows-10-10.0.17763-SP0
2020-06-03 17:47:25 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'sobooks',
 'LOG_FILE': 'test',
 'LOG_LEVEL': 'INFO',
 'NEWSPIDER_MODULE': 'sobooks.spiders',
 'SPIDER_MODULES': ['sobooks.spiders']}
2020-06-03 17:47:25 [scrapy.extensions.telnet] INFO: Telnet Password: d0676a790133ab44
2020-06-03 17:47:25 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2020-06-03 17:47:26 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2020-06-03 17:47:26 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2020-06-03 17:47:26 [scrapy.middleware] INFO: Enabled item pipelines:
['sobooks.pipelines.MysqlPipline']
2020-06-03 17:47:26 [scrapy.core.engine] INFO: Spider opened
2020-06-03 17:47:26 [sotag] INFO: sotag connect mysql:{'host': '127.0.0.1', 'port': 3306, 'user': 'root', 'db': 'sobooks', 'passwd': ''}
2020-06-03 17:47:26 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2020-06-03 17:47:26 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '小说'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '小说'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '小说'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '文学'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '文学'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '文学'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '历史'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '历史'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '历史'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '日本'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '日本'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '日本'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '管理'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '管理'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '管理'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '科普'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '科普'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '科普'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '推理'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '推理'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '推理'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '社会'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '社会'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '社会'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '传记'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '传记'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '传记'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '经济'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '经济'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '经济'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '悬疑'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '悬疑'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '悬疑'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '美国'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '美国'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '美国'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '哲学'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '哲学'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '哲学'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '心理'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '心理'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '心理'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '金融'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '金融'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '金融'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '商业'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '商业'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '商业'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '随笔'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '随笔'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '随笔'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '经典'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '经典'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '经典'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '思维'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '思维'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '思维'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '投资'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '投资'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '投资'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '文化'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '文化'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '文化'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '科幻'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '科幻'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '科幻'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '励志'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '励志'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '励志'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '成长'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '成长'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '成长'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '英国'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '英国'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '英国'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '中国'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '中国'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '中国'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '政治'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '政治'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '政治'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '纪实'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '纪实'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '纪实'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '艺术'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '艺术'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '艺术'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '生活'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '生活'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '生活'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '职场'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '职场'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '职场'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '科学'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '科学'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '科学'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '互联网'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '互联网'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '互联网'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '漫画'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '漫画'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '漫画'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '散文'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '散文'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '散文'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '法国'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '法国'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '法国'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '股票'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '股票'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '股票'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '奇幻'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '奇幻'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '奇幻'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '营销'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '营销'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '营销'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '二战'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '二战'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '二战'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '战争'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '战争'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '战争'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '德国'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '德国'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '德国'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '创业'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '创业'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '创业'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '女性'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '女性'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '女性'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '军事'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '军事'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '军事'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '名著'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '名著'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '名著'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '学习'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '学习'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '学习'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '爱情'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '爱情'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '爱情'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '人物'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '人物'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '人物'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '世界'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '世界'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '世界'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '绘本'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '绘本'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '绘本'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '理财'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '理财'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '理财'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '教育'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '教育'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '教育'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [sotag] INFO: get item:{'name': '国学'}
2020-06-03 17:47:27 [sotag] INFO: sotag process_item:{'name': '国学'}
2020-06-03 17:47:27 [scrapy.core.scraper] ERROR: Error processing {'name': '国学'}
Traceback (most recent call last):
  File "f:\programdata\anaconda3\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "f:\programdata\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 154, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "H:\mywork\blog\scrapy\sobooks\sobooks\pipelines.py", line 62, in process_item
    if self.alltags.has_key(item['name'])==True:
AttributeError: 'dict' object has no attribute 'has_key'
2020-06-03 17:47:27 [scrapy.core.engine] INFO: Closing spider (finished)
2020-06-03 17:47:27 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 210,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 9085,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'elapsed_time_seconds': 1.194961,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2020, 6, 3, 9, 47, 27, 784400),
 'log_count/ERROR': 54,
 'log_count/INFO': 119,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2020, 6, 3, 9, 47, 26, 589439)}
2020-06-03 17:47:27 [scrapy.core.engine] INFO: Spider closed (finished)
2020-06-03 17:49:17 [scrapy.utils.log] INFO: Scrapy 2.0.1 started (bot: sobooks)
2020-06-03 17:49:17 [scrapy.utils.log] INFO: Versions: lxml 4.5.0.0, libxml2 2.9.9, cssselect 1.1.0, parsel 1.5.2, w3lib 1.21.0, Twisted 20.3.0, Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)], pyOpenSSL 19.1.0 (OpenSSL 1.1.1d  10 Sep 2019), cryptography 2.8, Platform Windows-10-10.0.17763-SP0
2020-06-03 17:49:17 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'sobooks',
 'LOG_FILE': 'test',
 'LOG_LEVEL': 'INFO',
 'NEWSPIDER_MODULE': 'sobooks.spiders',
 'SPIDER_MODULES': ['sobooks.spiders']}
2020-06-03 17:49:17 [scrapy.extensions.telnet] INFO: Telnet Password: 0d3f2ccfcc7aa3ee
2020-06-03 17:49:17 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2020-06-03 17:49:18 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2020-06-03 17:49:18 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2020-06-03 17:49:18 [scrapy.middleware] INFO: Enabled item pipelines:
['sobooks.pipelines.MysqlPipline']
2020-06-03 17:49:18 [scrapy.core.engine] INFO: Spider opened
2020-06-03 17:49:18 [sotag] INFO: sotag connect mysql:{'host': '127.0.0.1', 'port': 3306, 'user': 'root', 'db': 'sobooks', 'passwd': ''}
2020-06-03 17:49:18 [sotag] INFO: get alltags
2020-06-03 17:49:18 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2020-06-03 17:49:18 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '小说'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '小说'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:小说
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '文学'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '文学'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:文学
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '历史'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '历史'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:历史
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '日本'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '日本'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:日本
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '管理'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '管理'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:管理
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '科普'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '科普'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:科普
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '推理'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '推理'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:推理
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '社会'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '社会'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:社会
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '传记'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '传记'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:传记
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '经济'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '经济'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:经济
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '悬疑'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '悬疑'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:悬疑
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '美国'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '美国'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:美国
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '哲学'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '哲学'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:哲学
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '心理'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '心理'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:心理
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '金融'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '金融'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:金融
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '商业'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '商业'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:商业
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '随笔'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '随笔'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:随笔
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '经典'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '经典'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:经典
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '思维'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '思维'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:思维
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '投资'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '投资'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:投资
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '文化'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '文化'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:文化
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '科幻'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '科幻'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:科幻
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '励志'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '励志'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:励志
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '成长'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '成长'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:成长
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '英国'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '英国'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:英国
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '中国'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '中国'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:中国
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '政治'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '政治'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:政治
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '纪实'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '纪实'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:纪实
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '艺术'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '艺术'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:艺术
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '生活'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '生活'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:生活
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '职场'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '职场'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:职场
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '科学'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '科学'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:科学
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '互联网'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '互联网'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:互联网
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '漫画'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '漫画'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:漫画
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '散文'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '散文'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:散文
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '法国'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '法国'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:法国
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '股票'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '股票'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:股票
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '奇幻'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '奇幻'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:奇幻
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '营销'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '营销'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:营销
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '二战'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '二战'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:二战
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '战争'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '战争'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:战争
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '德国'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '德国'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:德国
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '创业'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '创业'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:创业
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '女性'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '女性'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:女性
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '军事'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '军事'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:军事
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '名著'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '名著'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:名著
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '学习'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '学习'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:学习
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '爱情'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '爱情'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:爱情
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '人物'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '人物'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:人物
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '世界'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '世界'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:世界
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '绘本'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '绘本'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:绘本
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '理财'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '理财'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:理财
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '教育'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '教育'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:教育
2020-06-03 17:49:19 [sotag] INFO: get item:{'name': '国学'}
2020-06-03 17:49:19 [sotag] INFO: sotag process_item:{'name': '国学'}
2020-06-03 17:49:19 [sotag] INFO: tag exit:国学
2020-06-03 17:49:19 [scrapy.core.engine] INFO: Closing spider (finished)
2020-06-03 17:49:19 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 210,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 9063,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'elapsed_time_seconds': 0.903513,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2020, 6, 3, 9, 49, 19, 426908),
 'item_scraped_count': 54,
 'log_count/INFO': 174,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2020, 6, 3, 9, 49, 18, 523395)}
2020-06-03 17:49:19 [scrapy.core.engine] INFO: Spider closed (finished)
